### ISSUE TITLE
B Button on physical controller opens menu

### ISSUE THREAD

**Issue by fedeharuchan** [Lime3DS/Lime-3DS-Emulator#1101]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

all

### Description of Issue

pressing the B button on my 8bitdo ultimate 2c opens the emulator menu 

https://github.com/user-attachments/assets/739a67c3-5a00-4c67-887f-f95dc7d2a89d

### Expected Behavior

should generate an input in the game

### Reproduction Steps

open the game>press B button on controller

### System Configuration

CPU: Snapdragon 680
GPU/Driver: Native
RAM: 4gb 
OS: Android 13

**Comment by OpenSauce04** [comment]
Have you bound the controller's buttons in the emulator settings? This shouldn't happen if they have been.

**Comment by fedeharuchan** [comment]
yes ![Image](https://github.com/user-attachments/assets/f6af9a36-5193-4af1-a1af-398b970c5d44)

**Comment by Rummyster** [comment]
I'm also running into this issue. Doesn't seem to matter how I have the buttons bound.

Edit: after adding azahar to Daijisho launcher on android and launching the game through that I no longer get this error. But I still do if launched directly through azahar alone.

**Comment by fedeharuchan** [comment]
the issue remains when launching through es-de

**Comment by nikmagick** [comment]
Same issue here (through es-ds).  Retroid pocket 5

**Comment by fedeharuchan** [comment]
im not sure how i fixed it. but i think it was by rebinding the keys when the game was open.

**Comment by inigosm** [comment]
Go to settings > system > turn off "new 3ds mode". Seems to do it for me

**Comment by OpenSauce04** [comment]
> Go to settings > system > turn off "new 3ds mode". Seems to do it for me

This is completely unrelated, and I wouldn't recommend turning that setting off.

IIRC there have been a handful of changes over time which have aimed to address issues like this, most recently this one which was included in the last update: https://github.com/azahar-emu/azahar/pull/1122

I would imagine that this issue was simply fixed in an update rather than being related to any setting that was changed.

I'm going close this under the assumption that it has been resolved. If you still experience issues *on the latest version*, please open a new issue.

**Comment by isaiaswqx** [comment]
Has anyone fixed this issue ? Been trying to play Pokémon ultra moon and it’s unplayable

**Comment by Skynots** [comment]
Still not fixe, i have retroid pocket 5 azahar from obtenium all updated and still have same issu. Turn off new 3ds didn't work. But i did remape my controller in game + overlay option => réinitialisation off overlay and now it works !

**Comment by Techsteps** [comment]
Yes, this is still happening for me on Ayn Thor after running from Emulation Station.

**Comment by jackfrost2012** [comment]
This is still happening for me on Ayn Thor as well, running Azahar directly

**Comment by fernandogonzalezvera-droid** [comment]
Just to add to this conversation.
I have the latest version of Azahar, with the latest version of Retroid OS. I am using a Nintendo Switch Pro controller.
While using the controller I have found two variations of this issue. One when launching from a frontend (I use Es-De) and another when launching from the android OS.
a) When launching from a frontend, I get the "B button also inputs the back button" bug. That is, every time I press the B button, the menu gets on screen.
b) When launching from the normal OS, the back button does not work calling the menu. If I do not have anything bound to it, it just leaves the app and goes to home menu with a single click. (Exactly like pressing the home button twice). So what I did to workaround, was bind the back button to "close game" (Hey, at least I can close something!).

If I am not using the controller, but the normal pad from retroid launching from main screen does not seem to trigger the bug.

**Comment by COca-CO-la** [comment]
In my case I am using gamesir's x5s and in this case not just the B button, even the D-pad can't work properly in the Emu (While in the citra-mmj fork won't happen.)

**Comment by COca-CO-la** [comment]
> Still not fixe, i have retroid pocket 5 azahar from obtenium all updated and still have same issu. Turn off new 3ds didn't work. But i did remape my controller in game + overlay option => réinitialisation off overlay and now it works !

Is that `réinitialisation off overlay` an option in azahar or an option in RP5's OS?

**Comment by TehEpikBoi** [comment]
3 months later after the latest post, same issue. Citra mmj worked fine however when clicking B (yes I have mapped it) recognizes it as back. This pisses me off so much. I also have the gamesir x5 lite, I am running the latest version of the application on my phone through the google playstore (tried downloading the one from github same issue) and why is this closed.

EDIT:
Fixed now lol

**Comment by DavidRGriswold** [comment]
If this happens, it is because azahar is not recognizing the button pressed as a mapped button, so it is passing the command the controller makes to the system. And by default android maps the b button to back when it is not used for anything else. Remapping the b button should, in almost every case, solve the problem, as then Azahar will recognize it is a button and should capture and swallow the input. 

We could conceivably catch the B button press and block it opening the menu, but there's a chance that might break other things, which is why we have not done that. I know it can be frustrating when it happens so by all means add more comments here if it happens to you so we can watch for a more consistent pattern than we have seen so far.

**Comment by teskatory** [comment]
> > Go to settings > system > turn off "new 3ds mode". Seems to do it for me
> 
> This is completely unrelated, and I wouldn't recommend turning that setting off.
> 
> IIRC there have been a handful of changes over time which have aimed to address issues like this, most recently this one which was included in the last update: [#1122](https://github.com/azahar-emu/azahar/pull/1122)
> 
> I would imagine that this issue was simply fixed in an update rather than being related to any setting that was changed.
> 
> I'm going close this under the assumption that it has been resolved. If you still experience issues _on the latest version_, please open a new issue.

this is ACTUALLY the ONLY thing that fixed the issue for me, in july 2026. a remapping did NOTHING. azahar v2125 1.3vanilla on ayn thor. it was completely fine until i did my first restart on the device. after booting back up the device did not detect the SD card which all my roms are on. and then b opened the azahar menu instead of functioning as B. i remapped to R, and then back to b, and it still did the same thing. theni i turned off "new 3ds mode" and IMMEDIATELY the issue was fixed.
