### ISSUE TITLE
Azahar will sometimes default to other languages if 2 or more are installed

### ISSUE THREAD

**Issue by Coderst1** [Lime3DS/Lime-3DS-Emulator#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All versions

### Description of Issue

If for example English and Japanese are installed, Lime3DS will default to Japanese

### Expected Behavior

In this case, if the users desktop is set to English, Lime3DS should be in English, not Japanese

### Reproduction Steps

Download Japanese, Korean, French or any other language and try out Lime3DS

### Log File

I can't as my Laptop is fudged rn :(

### System Configuration

Should happen with most platforms except Android from What I've seen and done myself

**Comment by OpenSauce04** [comment]
I personally have replicated this issue on my Macbook Pro, and many other users have reported the issue. Definitely worth investigating ASAP as it dampens the user's first impression.

**Comment by OpenSauce04** [comment]
I will be moving this down to 2118 due to being temporarily unable to access my MacBook Pro, the only device I replicated this bug on.

**Comment by OpenSauce04** [comment]
Fixed by #358

**Comment by ghost** [comment]
It  doesn't seem to actually get fixed by https://github.com/Lime3DS/Lime3DS/pull/358

I'm seeing reports of it still happening, so I'm re-opening this 

I'll need to restart testing on linux and windows, Hopefully i can reproduce it again on one of these systems and maybe fix it this time for all users

**Comment by ghost** [comment]
![image-9.png](https://github.com/user-attachments/assets/1c322982-94ff-4e72-b92c-fc72076339a5)

Lime3DS 2118 defaulting to russian when it shouldn't  (Not my screenshot)

**Comment by ghost** [comment]
I still can't recreate this issue on my system 

Proper steps to reproduce this bug would be nice

**Comment by Kaizo107** [comment]
I am also experiencing this issue on Windows 10 with both the installer and portable versions, have English and Japanese installed, program always runs in Japanese.

**Comment by DVN-Divine** [comment]
![image_2024-11-08_115409057](https://github.com/user-attachments/assets/7c02d98d-199c-4211-9a44-e60d8ab50c3a)
I also have this problem, I have a russian keyboard installed on windows but it isn't set to my device language

**Comment by AkiraJkr** [comment]
Clean Azahar's RC1 install. Windows 11 24H2. Does persist between different sessions.

Windows Language Window if it's of any use;
![Image](https://github.com/user-attachments/assets/64d8078d-2f2f-4809-80c3-c8f098662368)

And here's how this looks in Azahar's Settings menu);
(I did notice Japanese is missing strings for quite a a bit of stuff though, like the many languages available

https://github.com/user-attachments/assets/9a161f82-00b2-499d-8484-194b0c044b69

logs

[azahar_log.old.txt](https://github.com/user-attachments/files/19265976/azahar_log.old.txt)
[azahar_log.txt](https://github.com/user-attachments/files/19265977/azahar_log.txt)


I wasn't sure if old issues that predated Azahar still counted so I accidentally made an duplicate. So putting the information here to keep it updated.

**Comment by AliciaJewel** [comment]
It's also worth noting that there's no English option in the language select menu.

**Comment by AliciaJewel** [comment]
Update: Selecting the below in the menu changed the language to English. There was still some Japanese text in the options, but that went back to English after the menu was closed and reopened.

![Image](https://github.com/user-attachments/assets/43df3e30-ef8d-4a91-8a51-8de59f948baf)

[azahar_log.old.txt](https://github.com/user-attachments/files/19277330/azahar_log.old.txt)
[azahar_log.txt](https://github.com/user-attachments/files/19277331/azahar_log.txt)

**Comment by detheavn** [comment]
I had the same issue, but tinkered a bit with the windows settings and to me it looks like it goes by Windows' Regional Format rather than System Language?

The application defaults to (mostly) Dutch with the following settings:

- Windows display langauge: English (United States).
- Country or region: Netherlands.
- Regional format: Dutch (Netherlands).
- Language in is <System>.

![Image](https://github.com/user-attachments/assets/f0d7a0c5-b9e7-4f95-a607-41de46a7846c)

It defaults to English with the following settings:

- Windows display langauge: English (United States).
- Country or region: Netherlands.
- Regional format: English (Netherlands).
- Language is is automatically changed from <System> to English by Azahar application.

![Image](https://github.com/user-attachments/assets/7633ed77-f6f6-4558-930d-025cede3f29d)

If I try to manually set it back to <System> it will immediately set it back to English. Overriding to another specific language, like German, does work.

**Comment by NoodleSushi** [comment]
I had to uninstall Chinese in my "Preferred languages" settings in Windows 10 to switch back to English, even though English (United States) is the first language in the list.

**Comment by leilaplaysya** [comment]
> Update: Selecting the below in the menu changed the language to English. There was still some Japanese text in the options, but that went back to English after the menu was closed and reopened.
> 
> ![Image](https://github.com/user-attachments/assets/43df3e30-ef8d-4a91-8a51-8de59f948baf)
> 
> [azahar_log.old.txt](https://github.com/user-attachments/files/19277330/azahar_log.old.txt) [azahar_log.txt](https://github.com/user-attachments/files/19277331/azahar_log.txt)

This helped. It is in English now. Thanks.

**Comment by seamonkey420** [comment]
Latest Azahar for MacOS does not detect system language properly. I am in USA and have English set. Azahar opens w/System set as language but shows everything in spanish. change to english in UI

**Comment by melodycat9** [comment]
<img width="877" height="881" alt="Image" src="https://github.com/user-attachments/assets/af457817-44bc-47d7-936a-6b571fc2c3f3" />

<img width="1263" height="577" alt="Image" src="https://github.com/user-attachments/assets/892f90c2-f660-4c55-88e3-4981fa0baa86" />

Installed Azahar for the first time today and it's in Korean. Everything in my Windows settings is set to English but I have Korean installed

**Comment by RingtailRaider** [comment]
Happening still in Windows 10, I installed a few languages just for easier keyboard layout access and it decided to pick the third one of those (german, apparently) as the "system default" language, despite literally everything in my os being set to US English as its default language and region.

**Comment by OpenSauce04** [comment]
This will be fixed in 2126.0. The fix is not yet in a live release.
