### ISSUE TITLE
Fire Emblem Echoes - DLC map does not display correctly

### ISSUE THREAD

**Issue by OmegaZeroXIII** [Lime3DS/Lime-3DS-Emulator#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Build 2118

### Description of Issue

Upon entering the first DLC map of the pre-game story (the liberators' maps) it loads without textures for most of the game except for the bridges.

![imagen_2024-09-21_192139211](https://github.com/user-attachments/assets/e13f0242-c3b3-451a-a62b-32e40edc262c)

### Expected Behavior

Attached is a preview of the map extracted from the Fire Emblem WoD page.

![imagen_2024-09-21_192406884](https://github.com/user-attachments/assets/b451abc2-56b0-4137-91f5-908614bd4499)

### Reproduction Steps

- Start game
- Load a saved game
- Enter DLC menu
- Load DLC Map

### Log File

[citra_log.txt](https://github.com/user-attachments/files/17087812/citra_log.txt)

### System Configuration

CPU: AMD Ryzen 5 5600G
GPU/Driver: AMD APU Driver 24.7.1 2GB VRAM
RAM: 16GB
OS: Windows 11

**Comment by OmegaZeroXIII** [comment]
As a side note, I don't know if it has anything to do with it, but the game won't let you use the savestates if you install the DLC. It comes up with an error and just when you close the error window the textures return.

![imagen_2024-09-21_195808844](https://github.com/user-attachments/assets/e436a172-83b1-4ed8-b276-412aeaa6a510)

**Comment by OpenSauce04** [comment]
It seems that you have uploaded the wrong log file. Please upload the file named `lime3ds_log.txt`, ensuring that the log was generated when this issue occurred.

**Comment by OmegaZeroXIII** [comment]
[lime3ds_log.zip](https://github.com/user-attachments/files/17090458/lime3ds_log.zip)

Here is the log attached. I had to compress it but here is recorded all the game session I had yesterday of FE... by the way this same error happened to me in a map of the main story too and I tried to do the same.

Save a savestate and as soon as the error came out I closed the window and the textures were fixed.

**Comment by Soup-Doup** [comment]
I know I'm a bit late but If your using Citra, there is a problem when loading textures using the native resolution. Go into the emulation settings -> configure -> Graphics -> Resolution and change it to 2x the native resolution and load into the map.

**Comment by OpenSauce04** [comment]
Does this issue still happen with Azahar?

**Comment by ilikepizza107** [comment]
Hello, yes, this is still an issue with Azahar. I'm not sure why, but the game suddenly decided to give this issue to me as well

![Image](https://github.com/user-attachments/assets/f1a16d56-d18e-40de-9a02-c88d98632ffb)

**Comment by ilikepizza107** [comment]
This is also possibly related to https://github.com/azahar-emu/azahar/issues/514

**Comment by ilikepizza107** [comment]
I have yet to get this bug again in Azahar 2123.2
